exclude: ^docs
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-ast
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    -   id: isort
        args: [--line-length=120, --profile=black, --project=hrcore]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=120, --skip-string-normalization]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-mutable, flake8-simplify]
        args: [--max-line-length=120, '--ignore=E203,W503,SIM106']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
